### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by jaysunneu** [sumingyd/Telecom-Shandong-IPTV-List#2]
请问有4k源或者高清源吗，看频道名称不能区分出来。

**Comment by sumingyd** [comment]
里面记得好像有，有也只是有1-2个

**Comment by wxg4net** [comment]
山东电信高清源有一些高清频道（含地方），估计有10+，完整的信号源见附件
[sddx.txt](https://github.com/sumingyd/Telecom-Shandong-IPTV-List/files/11076260/sddx.txt)

**Comment by sumingyd** [comment]
> 山东电信高清源有一些高清频道（含地方），估计有10+，完整的信号源见附件 [sddx.txt](https://github.com/sumingyd/Telecom-Shandong-IPTV-List/files/11076260/sddx.txt)

今晚我测试一下。不重复的会更新上去。感谢提供。

**Comment by sumingyd** [comment]
已更新
